services:
  db:
    image: postgres:17
    container_name: be_purchase_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - purchase_network

volumes:
  postgres_data:

networks:
  purchase_network:
    driver: bridge
